SocialGouv/docker

k8s-ns-killer/.gitlab-ci.yml
k8s-ns-killer/bin/k8s-ns-killer

refactor(k8s-ns-killer): change git branch exist check

---

git-deploy/.gitlab-ci.yml
helm/.gitlab-ci.yml
k8s-ns-killer/.gitlab-ci.yml
kubectl/.gitlab-ci.yml

ci(gitlab): run jobs based on modified files

---

nginx4spa/.gitlab-ci.yml

test(nginx4spa): use solid tests :muscle:

---

nginx4spa/README.md
nginx4spa/envsub.sh

docs(nginx4spa): update README

---

.gitlab-ci.yml
curl/.gitlab-ci.yml
curl/Dockerfile
git-deploy/.gitlab-ci.yml
git-deploy/Dockerfile
git-tag-release/.gitlab-ci.yml
git-tag-release/Dockerfile
helm/.gitlab-ci.yml
helm/Dockerfile
k8s-ns-killer/.gitlab-ci.yml
k8s-ns-killer/Dockerfile
kubectl/.gitlab-ci.yml
kubectl/Dockerfile
nginx4spa/.gitlab-ci.yml

feat: add hadolint

---

kubectl/.gitlab-ci.yml
kubectl/Dockerfile

refactor(kubectl): change home and remove ADD

---

curl/.gitlab-ci.yml
git-deploy/.gitlab-ci.yml
git-tag-release/.gitlab-ci.yml
helm/.gitlab-ci.yml
k8s-ns-killer/.gitlab-ci.yml
kubectl/.gitlab-ci.yml
nginx4spa/.gitlab-ci.yml

ci(gitlab): link jobs with needs

---

.gitlab-ci.yml
README.md
infra-ansible-ci/.gitlab-ci.yml
infra-ansible-ci/Dockerfile
infra-ansible-ci/README.md
kubectl/.gitlab-ci.yml

Move in this repository infra-ansible-ci image (from https://gitlab.factory.social.gouv.fr/infra/images-docker) + format it as expected in this repo

feat(infra-ansible-ci) : import image from images-docker repository

---

infra-ansible-ci/Dockerfile

yq is missing and is required : so add it in this image

feat(infra-ansible-ci) add missing yq tools in image

---

curl/.gitlab-ci.yml
curl/Dockerfile
git-deploy/.gitlab-ci.yml
git-deploy/Dockerfile
git-tag-release/Dockerfile
helm/.gitlab-ci.yml
helm/Dockerfile
infra-ansible-ci/.gitlab-ci.yml
k8s-ns-killer/.gitlab-ci.yml
k8s-ns-killer/Dockerfile
kubectl/.gitlab-ci.yml
kubectl/Dockerfile
nginx4spa/.gitlab-ci.yml

feat: use partial pin to master version glob

---

.gitlab-ci.yml
README.md
puppetteer/.gitlab-ci.yml
puppetteer/Dockerfile
puppetteer/README.md

feat(puppetteer): add common puppetteer image

---

nginx4spa/.gitlab-ci.yml
nginx4spa/README.md
nginx4spa/envsub.sh
nginx4spa/nginx.conf

feat(nginx4spa): configurable PORT

---

k8s-ns-killer/.gitlab-ci.yml

test(k8s-ns-killer): assert that it works :)

---

kubectl/Dockerfile

feat(kubectl): update kubectl to 0.17.0

---

.gitlab-ci.yml
README.md
wait-for-postgres/.gitlab-ci.yml
wait-for-postgres/Dockerfile
wait-for-postgres/README.md
wait-for-postgres/bin/wait-for-postgres

feat(wait-for-postgres): add wait-for-postgres image

---

.gitlab-ci.yml
k8s-cleaner/.gitlab-ci.yml
k8s-cleaner/Dockerfile
k8s-cleaner/README.md
k8s-cleaner/bin/clean.k8s.js
k8s-ns-killer/README.md

I have problem with test since a don't know how create temporary object and don't know how assert the results
any help is welcome :)

feat(k8s-object-cleaner): add a k8s object cleaner

---

kubectl/Dockerfile

fix(kubectl): update kubectl to 0.17.3

---

infra-ansible-ci/Dockerfile

fix(infra-ansible-ci): update infra image deps

---

azure-db/.gitlab-ci.yml
azure-db/bin/export_from_k8s_secret
azure-db/test/export_from_k8s_secret
azure-db/test/setup_dir/fixtures/secret.json

feat(azure-db): add export_from_k8s_secret function

---

azure-db/.gitlab-ci.yml
azure-db/Dockerfile

feat(azure-db): kubctl and jq to the azure-db image

---

azure-db/.gitlab-ci.yml
azure-db/bin/export_from_k8s_secret
azure-db/test/export_from_k8s_secret

fix(azure-db): make export_from_k8s_secret executable

---

azure-db/bin/export_from_k8s_secret
azure-db/test/export_from_k8s_secret
azure-db/test/setup_dir/fixtures/secret.json

fix(azure-db): handle special chars

---

kubectl/Dockerfile

fix(kubectl): update kubectl tag to v1.17.4

---

.gitlab-ci.yml

ci(gitlab): do not build PRs

---

kubectl/Dockerfile

---
BREAKING CHANGE: **kubectl**: remove unneeded image bin
- `sudo` in the image is a bad thing...

feat(kubectl)!: remove unneeded image bin

---

helm/.gitlab-ci.yml
helm/Dockerfile

feat(helm): add bats bin and libs

---

.gitlab-ci.yml
bats/.gitlab-ci.yml
bats/Dockerfile
bats/README.md
bats/test/assert.bats
bats/test/files.bats
bats/test/kitchen.bats
bats/test/test_helper.bash

 feat(bats): add socialgouv/docker/bats image

---

kubectl/Dockerfile
kubectl/requirements.yml

refactor(kubectl): use bitnami/kubectl image

---

kubectl/.gitlab-ci.yml
kubectl/Dockerfile

fix(kubectl): add up to date bash version

---

kubectl/.gitlab-ci.yml
kubectl/Dockerfile

fix(kubectl): add up to date coreutils version

---

helm/Dockerfile

Revert "feat(deps): update socialgouv/docker/kubectl docker tag to v1.6.2"

---

kubectl/.gitlab-ci.yml
kubectl/Dockerfile

feat(kubectl): add kustomize to kubectl image

---

.gitlab-ci.yml
README.md
trivy/.gitlab-ci.yml
trivy/Dockerfile
trivy/README.md

feat(trivy): add trivy image

---

kubectl/Dockerfile
kubectl/go.mod

chore(kubectl): remove unused go.mod

---

k8s-ns-killer/bin/k8s-ns-killer

fix(k8s-ns-killer): do not remove ns linked to existing tags

---

azure-db/bin/clean-dbs

add a `clean-dbs` script. will drop old generated dbs older than 10 days

feat:(azure-db): add clean-dbs command

---

.gitlab-ci.yml
README.md
azure-cli/.gitlab-ci.yml
azure-db/.gitlab-ci.yml
bats/.gitlab-ci.yml
curl/.gitlab-ci.yml
fluentd-modsecurity/.gitlab-ci.yml
git-deploy/.gitlab-ci.yml
git-tag-release/.gitlab-ci.yml
helm/.gitlab-ci.yml
infra-ansible-ci/.gitlab-ci.yml
k8s-ns-killer/.gitlab-ci.yml
k8s-object-cleaner/.gitlab-ci.yml
kosko/.gitlab-ci.yml
kubectl/.gitlab-ci.yml
nginx4spa/.gitlab-ci.yml
pg-cleaner/.gitlab-ci.yml
puppeteer/.gitlab-ci.yml
trivy/.gitlab-ci.yml
wait-for-postgres/.gitlab-ci.yml

Hope this works as expected
Add change: rules for every image

fix(gitlab): add rules.change

---

.gitlab-ci.yml

ci(gitlab): continuous release

---

azure-db/Dockerfile

Add git into azure-db so clean-dbs command can use git history

fix(azure-db): add git

---

bats/Dockerfile

Revert "feat(deps): update bats/bats docker tag to v1.2.1"

---

infra-ansible-ci/Dockerfile

fix(infra-ansible-ci): update image apt dependencies

---

.github/renovate.json

24 daily jobs for each failing PR is way too much

chore(renovate): use SocialGouv/renovate-config:light

---

azure-db/.gitlab-ci.yml
wait-for-postgres/.gitlab-ci.yml
wait-for-postgres/Dockerfile

Revert "feat(deps): update postgres docker tag to v13"

---

nginx4spa/nginx.conf

fix(nginx4spa): fix $uri/ order

---

wait-for-postgres/.gitlab-ci.yml
wait-for-postgres/bin/wait-for-postgres

---
BREAKING CHANGE: wait-for-postgres will now fail if the user, password, database is not correct

feat(wait-for-postgres)!: use psql command

---

azure-cli/.gitlab-ci.yml
azure-db/.gitlab-ci.yml
bats/.gitlab-ci.yml
curl/.gitlab-ci.yml
fluentd-modsecurity/.gitlab-ci.yml
git-deploy/.gitlab-ci.yml
git-tag-release/.gitlab-ci.yml
helm/.gitlab-ci.yml
infra-ansible-ci/.gitlab-ci.yml
k8s-ns-killer/.gitlab-ci.yml
k8s-object-cleaner/.gitlab-ci.yml
kosko/.gitlab-ci.yml
kubectl/.gitlab-ci.yml
nginx4spa/.gitlab-ci.yml
pg-cleaner/.gitlab-ci.yml
puppeteer/.gitlab-ci.yml
trivy/.gitlab-ci.yml
wait-for-postgres/.gitlab-ci.yml

ci(gitlab): test if files in subdir changes too

---

puppeteer/Dockerfile

feat(puppeteer): update chromium to v86

---

kosko/.gitlab-ci.yml
kosko/Dockerfile

feat(kosko): add kapp bin

---

azure-db/bin/drop-autodevops-dbs

the SET read/write was not applied as executed in another psql session

fix(azure-db): ensure read-write is active for drop session

---

wait-for-http/.gitlab-ci.yml

test(wait-for-http): allow to wait exactly 5 sec

---

azure-cli/.gitlab-ci.yml
azure-db/.gitlab-ci.yml
bats/.gitlab-ci.yml
curl/.gitlab-ci.yml
fluentd-modsecurity/.gitlab-ci.yml
git-deploy/.gitlab-ci.yml
git-tag-release/.gitlab-ci.yml
helm/.gitlab-ci.yml
infra-ansible-ci/.gitlab-ci.yml
k8s-ns-killer/.gitlab-ci.yml
k8s-object-cleaner/.gitlab-ci.yml
kosko/.gitlab-ci.yml
kubectl/.gitlab-ci.yml
nginx4spa/.gitlab-ci.yml
pg-cleaner/.gitlab-ci.yml
puppeteer/.gitlab-ci.yml
trivy/.gitlab-ci.yml
wait-for-postgres/.gitlab-ci.yml

ci(gitlab): ensure to run pipeline on master .gitlab-ci.yaml changes

---

helm/.gitlab-ci.yml
helm/Dockerfile

Revert "feat(deps): update alpine/helm docker tag to v3"

---

helm/.gitlab-ci.yml
kosko/.gitlab-ci.yml
kosko/Dockerfile
kosko/package.json

chore(kosko): make kosko image renovate friendly

---

bats/.gitlab-ci.yml

ci(gitlab): add retry to the fuzzy duration based bats test

---

.github/workflows/nginx4spa.yaml
.gitlab-ci.yml
nginx4spa/test/__setup.bash
nginx4spa/test/envsub.bats
nginx4spa/test/volume.bats

ci(github): github workflow for nginx4spa

---

.github/workflows/nginx4spa.yaml

ci(github): skip nginx4spa if no changes

---

azure-cli/Dockerfile

fix(azure-cli): update ca-certificates

---

k8s-ns-killer/Dockerfile

fix(k8s-ns-killer): update less

---

infra-ansible-ci/Dockerfile

styles(infra-ansible-ci): avoid use of cache directory with pip

---

pg-cleaner/Dockerfile

style(pg-cleaner): avoid use of cache directory with pip

---

k8s-object-cleaner/Dockerfile

chore(k8s-object-cleaner): update less and node

---

wait-for-postgres/bin/wait-for-postgres

Make wait-for-postgres more verbose so we can see the error before the end of the process :)

fix(wait-for-postgres): better debug

---

azure-db/bin/drop-db-user

---
Lock the database before disconnecting users to prevent reconnection before we drop the database

feat(azure-db): prevent foot in the door user reconnection

---

azure-db/bin/drop-db-user

fix(azure-db): fix single drop

---

kubectl/Dockerfile

see my comment in https://github.com/bitnami/bitnami-docker-kubectl/issues/9
and very convenient when working with kubectl scripts

feat(jq): json cli helper

---

kosko/Dockerfile
kubectl/Dockerfile

Reverts SocialGouv/docker#632
Refs: b260c6acfb6659f35bf80a4f43cd1844bd077342

revert(deps): update dependency jq to v1.6-r1

---

no-k8s/Dockerfile

revert(deps): update dependency socialgouv/k8s to v1.4.0

---

bats/Dockerfile
no-k8s/Dockerfile

revert(deps): update dependency git to v2.30.2-r0

---

dhall/Dockerfile

revert(deps): update dependency dhall-lang/dhall-haskell to v1.39.0

---

bats/Dockerfile

fix(bats): update to alpine:3.12

---

.github/workflows/check-cluster-images.tag.yaml
.github/workflows/check-cluster-images.yaml
check-cluster-images/Dockerfile
check-cluster-images/README.md
check-cluster-images/package.json
check-cluster-images/script.sh
package.json
yarn.lock

related to https://github.com/SocialGouv/support/issues/438

feat: add check-cluster-images

---

s3-client/Dockerfile
s3-client/dump-upload.sh

utilise les variables d'environnement uniquement

fix(s3): use env vars
